service: reunion-connect-backend
provider:
  name: aws
  runtime: nodejs24.x
  environment:
    DB_HOST: "database-1.cluster-cezswsoi8m3o.us-east-1.rds.amazonaws.com"
    DB_USER: "postgres"
    DB_NAME: "database-1.cluster-cezswsoi8m3o.us-east-1.rds.amazonaws.com"
    DB_PASSWORD: "your_database_password"
    DB_PORT: "5432"
  vpc: # Required to communicate with your RDS PostgreSQL DB
    securityGroupIds: [sg-09cee94df867cf754]
    subnetIds: [
      subnet-0dfdb663652cba578,
      subnet-08320caa36be4fa6c
    ]
  iam:
    role:
      statements: # Grants Lambda permission to use your S3 file bucket
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::reunion-connect/*"

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*' # Routes all incoming HTTP traffic to your Express app


# DB Hostname
#database-1.cluster-cezswsoi8m3o.us-east-1.rds.amazonaws.com
